---
title: "git_00"
author: "zaira gomez"
date: "August 2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with a sequence of commits to the master branch.
Our project will be done using several commits to the master branch.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->

## First Verse 
<!--Put the first five lines of a poem by Lewis Carrol in this section!-->
One winter night, at half-past nine,  
      Cold, tired, and cross, and muddy,  
I had come home, too late to dine,  
And supper, with cigars and wine,

 Was waiting in the study.  
      
      

## Second Verse
<!--Put the first five lines of a poem by Robert Frost here!-->
Two roads diverged in a yellow wood,  
And sorry I could not travel both  
And be one traveler, long I stood  
And looked down one as far as I could

To where it bent in the undergrowth;  

## Third Verse
<!--Put the first two verses of The Walrus and the Carpenter here!-->
"The sun was shining on the sea,    
      Shining He did his very best to make    
      The billows smooth and bright —    
And this was odd, because it was    
      The middle of the night.    

The moon was shining sulkily,    
      Because she thought the sun    
Had got no business to be there    
      After the day was done —    
"It's very rude of him," she said,    
      "To come and spoil the fun."with all his might:   
## Last Verse
<!--Put a short poem of your choice 8-20 lines,here!-->
It was many and many a year ago,    
   In a kingdom by the sea,    
That a maiden there lived whom you may know    
   By the name of Annabel Lee;    
And this maiden she lived with no other thought    
   Than to love and be loved by me.
   

I was a child and she was a child,    
   In this kingdom by the sea,    
But we loved with a love that was more than love—    
   I and my Annabel Lee—    
With a love that the wingèd seraphs of Heaven    
   Coveted her and me.    